name: vizia-server-cpu
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::cpuonly
  - flask
  - flask-socketio>=5.1.1
  - requests
  - jsonpickle
  - opencv
  - pandas