name: vizia-server-gpu
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytorch::pytorch
  - pytorch::torchvision
  - nvidia::cudatoolkit=11.1
  - opencv
  - libopencv
  - py-opencv
  - flask
  - flask-socketio>=5.1.1
  - requests
  - jsonpickle
  - pandas