wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    code_path: code/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1643954720
    t:
      1:
      - 1
      2:
      - 1
      4: 3.7.11
      5: 0.12.1
      8:
      - 5
    visualize:
      conf_mat:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: conf_mat_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
batch_size:
  desc: null
  value: 64
dataset_version:
  desc: null
  value: 3
epochs:
  desc: null
  value: 30
input_size:
  desc: null
  value: 384
lr:
  desc: null
  value: 0.00013088880219313634
model_name:
  desc: null
  value: resnet50
num_frozen:
  desc: null
  value: 2
num_workers:
  desc: null
  value: 12
root_path:
  desc: null
  value: /home/martin/datasets/Money_Classification
val_ratio:
  desc: null
  value: 0.3
weight_decay:
  desc: null
  value: 1.5482798850818048e-06
